nginx:
  replicaCount: 1

  image:
    repository: docker.for.mac.localhost:5000/egm/nginx-deployment
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 6060
    targetPort: 80
    protocol: TCP

web:
  replicaCount: 1

  image:
    repository: docker.for.mac.localhost:5000/egm/web-deployment
    tag: latest
    pullPolicy: IfNotPresent

  volumeMounts:
    mountPath: /var/www/html
  volumes:
    hostPath:
      path:

  service:
    type: LoadBalancer
    port: 9000
    protocol: TCP
