apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
  - port: {{ .Values.nginx.service.port }}
    targetPort: {{ .Values.nginx.service.targetPort }}
    protocol: {{ .Values.nginx.service.protocol }}
  selector:
    app: nginx-deployment
