apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  ports:
  - port: {{ .Values.web.service.port }}
    protocol: {{ .Values.web.service.protocol }}
  selector:
    app: web-deployment
