apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: {{ .Values.web.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web-deployment
              topologyKey: kubernetes.io/hostname
      containers:
      - name: web
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.web.service.port }}
{{ if .Values.web.volumeMounts }}
        volumeMounts:
            - mountPath: {{ .Values.web.volumeMounts.mountPath }}
              name: code
      volumes:
        - name: code
          hostPath:
            path: {{ .Values.web.volumes.hostPath.path }}
{{ end }}